Repository woowa-techcamp-2022/android-repo-02, pull requests merged in 2022-07, with the labels that each got.

#10 [ADD] #9 - icons
  presentation/src/main/res/drawable/ic_arrow_left.xml
  presentation/src/main/res/drawable/ic_bookmark.xml
  presentation/src/main/res/drawable/ic_check.xml
  presentation/src/main/res/drawable/ic_filter.xml
  presentation/src/main/res/drawable/ic_issue_closed.xml
  presentation/src/main/res/drawable/ic_issue_open.xml
  presentation/src/main/res/drawable/ic_link.xml
  presentation/src/main/res/drawable/ic_location.xml
  presentation/src/main/res/drawable/ic_mail.xml
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/drawable/ic_search_bold.xml
  presentation/src/main/res/drawable/ic_star.xml
  presentation/src/main/res/drawable/ic_user.xml
  presentation/src/main/res/drawable/ic_users.xml
  presentation/src/main/res/drawable/ic_variant10.xml
  presentation/src/main/res/drawable/ic_variant16.xml
Labels: add

#12 [ADD] #11 - hilt setting
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/repositorysearch/di/application/DaggerApplication.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
Labels: add

#16 [ADD] #15 - font family
  .idea/misc.xml
  presentation/src/main/.DS_Store
  presentation/src/main/res/.DS_Store
  presentation/src/main/res/font/outfit.xml
  presentation/src/main/res/font/outfit_black.ttf
  presentation/src/main/res/font/outfit_bold.ttf
  presentation/src/main/res/font/outfit_extra_bold.ttf
  presentation/src/main/res/font/outfit_extra_light.ttf
  presentation/src/main/res/font/outfit_light.ttf
  presentation/src/main/res/font/outfit_medium.ttf
  presentation/src/main/res/font/outfit_regular.ttf
  presentation/src/main/res/font/outfit_semi_bold.ttf
  presentation/src/main/res/font/outfit_thin.ttf
  presentation/src/main/res/values-night/themes.xml
  presentation/src/main/res/values/font_style.xml
  presentation/src/main/res/values/themes.xml
Labels: add

#18 [ADD] #17 - viewBinding Dependancy
  .idea/discord.xml
  presentation/build.gradle
Labels: add

#19 [FEAT] #2 main toolbar
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/ViewPagerAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/res/drawable/bg_gradient.xml
  presentation/src/main/res/drawable/bg_tab_ripple.xml
  presentation/src/main/res/drawable/box_tab_indicator.xml
  presentation/src/main/res/drawable/ic_search.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_issue.xml
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/menu_item_user_icon.xml
  presentation/src/main/res/menu/menu_toolbar_main.xml
  presentation/src/main/res/values/colors.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#21 [FEAT] #20 - resultActivity
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/ResultActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/ResultViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/FragmentManagement.kt
  presentation/src/main/res/layout/activity_result.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#23 [FIX] #22 - result activity
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/ResultActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/FragmentManagement.kt
Labels: fix

#24 Feature/1-login Github로 로그인 구현
  .DS_Store
  .idea/misc.xml
  data/.DS_Store
  data/build.gradle
  data/src/.DS_Store
  data/src/main/.DS_Store
  data/src/main/java/.DS_Store
  data/src/main/java/com/.DS_Store
  data/src/main/java/com/woowahan/data/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/auth/AuthService.kt
  data/src/main/java/com/woowahan/data/base/BaseDataSource.kt
  data/src/main/java/com/woowahan/data/entity/GitHubTokenData.kt
  domain/.DS_Store
  domain/src/.DS_Store
  domain/src/AndroidManifest.xml
  domain/src/main/.DS_Store
  domain/src/main/java/.DS_Store
  domain/src/main/java/com/.DS_Store
  domain/src/main/java/com/woowahan/domain/authUseCase/GetGitHubAccessTokenUseCase.kt
  domain/src/main/java/com/woowahan/domain/model/GitHubToken.kt
  domain/src/main/java/com/woowahan/domain/model/GitToken.kt
  domain/src/main/java/com/woowahan/domain/repository/AuthRepository.kt
  gradle.properties
  presentation/.DS_Store
  presentation/build.gradle
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/TokenInterceptor.kt
  presentation/src/main/res/layout/activity_login.xml
Labels: feature

#28 [REFACTOR] #27 - typeAuth, typeApi annotation 생성 후 연결
  .idea/misc.xml
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
Labels: enhancement

#29 [FEAT] #4 - profile
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/res/drawable/bg_repo_starred_icon.xml
  presentation/src/main/res/drawable/bg_type.xml
  presentation/src/main/res/drawable/bg_user_info.xml
  presentation/src/main/res/drawable/ic_star_outlined.xml
  presentation/src/main/res/font/ko_pub_dotum.xml
  presentation/src/main/res/font/ko_pub_dotum_bold.ttf
  presentation/src/main/res/font/ko_pub_dotum_light.ttf
  presentation/src/main/res/font/ko_pub_dotum_medium.ttf
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#26 [FIX] #25 - 시작 Activity를 LoginActivity로 변경
  presentation/src/main/AndroidManifest.xml
Labels: fix

#38 [REFACTOR] #36 - Mapping GitToken in dataSource
  data/src/main/java/com/woowahan/data/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/entity/GitHubTokenData.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
Labels: refactor

#46 [REFACTOR] #45 - rename to dividerItemDecoration
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/DividerItemDecoration.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
Labels: refactor

#43 Refactor/30 notification naming convention
  data/src/main/java/com/woowahan/data/entity/NotificationData.kt
  data/src/main/java/com/woowahan/data/entity/RepositoryData.kt
  data/src/main/java/com/woowahan/data/entity/SubjectData.kt
  data/src/main/java/com/woowahan/data/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationService.kt
  domain/src/main/java/com/woowahan/domain/model/Notification.kt
  domain/src/main/java/com/woowahan/domain/notificationUseCase/GetNotificationsUseCase.kt
  domain/src/main/java/com/woowahan/domain/repository/NotificationRepository.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/NotificationAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ApiHeaderInterceptor.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/TimeFormatter.kt
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/notification_item.xml
Labels: refactor

#39 Feature/5 notification 단순 구현
  data/src/main/java/com/woowahan/data/entity/NotificationData.kt
  data/src/main/java/com/woowahan/data/entity/RepositoryData.kt
  data/src/main/java/com/woowahan/data/entity/SubjectData.kt
  data/src/main/java/com/woowahan/data/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationService.kt
  domain/src/main/java/com/woowahan/domain/model/Notification.kt
  domain/src/main/java/com/woowahan/domain/notificationUseCase/GetNotificationsUseCase.kt
  domain/src/main/java/com/woowahan/domain/repository/NotificationRepository.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/NotificationAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ApiHeaderInterceptor.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/TimeFormatter.kt
Labels: feature

#44 [REFECTOR] #35 - notification view model
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
Labels: refactor

#49 [FIX] #48 - MainViewModel
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainViewModel.kt
Labels: fix

#51 Fix/48 notification import problem
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
Labels: fix

#55 [REFACTOR] #53 - toModel()을 dataSource에서 호출
  data/src/main/java/com/woowahan/data/auth/AuthDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/auth/AuthRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationRepositoryImpl.kt
Labels: refactor

#56 [REFACTOR] #52 - change coroutine to coroutine flow in notification
  domain/src/main/java/com/woowahan/domain/notificationUseCase/GetNotificationsUseCase.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
Labels: refactor

#57 [REFECTOR] #54 - Login
  domain/src/main/java/com/woowahan/domain/authUseCase/GetGitHubAccessTokenUseCase.kt
  presentation/src/main/AndroidManifest.xml
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
Labels: refector

#61 [DEL] #60 - LoginActivity noHistory option
  presentation/src/main/AndroidManifest.xml
Labels: fix

#63 [ADD] #58 - profile
  data/src/main/java/com/woowahan/data/entity/UserData.kt
  domain/src/main/java/com/woowahan/domain/model/User.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/TextViewExtension.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/loading/LoadingDialogFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/ResultActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileViewModel.kt
  presentation/src/main/res/layout/dialog_loading.xml
  presentation/src/main/res/layout/fragment_profile.xml
Labels: add

#65 [REFECTOR] #64 - MainActivity
  presentation/src/main/res/layout/activity_main.xml
Labels: refector

#68 [ADD] #58 - profile
  data/src/main/java/com/woowahan/data/user/UserDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/user/UserRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/user/UserService.kt
  domain/src/main/java/com/woowahan/domain/model/User.kt
  domain/src/main/java/com/woowahan/domain/repository/UserRepository.kt
  domain/src/main/java/com/woowahan/domain/userUseCase/GetUserUseCase.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
Labels: add

#67 [FEAT] #3 - Issue
  data/build.gradle
  data/src/main/java/com/woowahan/data/entity/IssueData.kt
  data/src/main/java/com/woowahan/data/entity/RepositoryData.kt
  data/src/main/java/com/woowahan/data/issue/IssueDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/issue/IssuePagingSource.kt
  data/src/main/java/com/woowahan/data/issue/IssueRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/issue/IssueService.kt
  domain/src/main/java/com/woowahan/domain/issueUseCase/GetIssueUseCase.kt
  domain/src/main/java/com/woowahan/domain/model/Issue.kt
  domain/src/main/java/com/woowahan/domain/repository/IssueRepository.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/FilterAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/IssueAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueViewModel.kt
  presentation/src/main/res/anim/anim_rotate_end.xml
  presentation/src/main/res/anim/anim_rotate_start.xml
  presentation/src/main/res/drawable/bg_filterbar_disabled.xml
  presentation/src/main/res/drawable/bg_filterbar_enabled.xml
  presentation/src/main/res/drawable/bg_filterbar_selector.xml
  presentation/src/main/res/drawable/ic_arrow_down.xml
  presentation/src/main/res/layout/fragment_issue.xml
  presentation/src/main/res/layout/item_issue.xml
  presentation/src/main/res/layout/spinner_filter_dropdown.xml
  presentation/src/main/res/layout/spinner_filter_top.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#71 [REFACTOR] #62 - Rename notification_item to item_notification
  .DS_Store
  .idea/compiler.xml
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/item_notification.xml
Labels: refector

#76 [FIX] #75 IssueFragment
  data/src/main/java/com/woowahan/data/entity/IssueData.kt
Labels: bug

#73 Fix/70 sync notification comments
  data/src/main/java/com/woowahan/data/entity/MessageData.kt
  data/src/main/java/com/woowahan/data/entity/NotificationData.kt
  data/src/main/java/com/woowahan/data/entity/OwnerData.kt
  data/src/main/java/com/woowahan/data/entity/SubjectData.kt
  data/src/main/java/com/woowahan/data/notification/NotificationDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/notification/NotificationService.kt
  domain/src/main/java/com/woowahan/domain/model/Message.kt
  domain/src/main/java/com/woowahan/domain/model/Notification.kt
  domain/src/main/java/com/woowahan/domain/model/Subject.kt
  domain/src/main/java/com/woowahan/domain/notificationUseCase/GetSubjectUseCase.kt
  domain/src/main/java/com/woowahan/domain/notificationUseCase/MarkNotificationAsReadUseCase.kt
  domain/src/main/java/com/woowahan/domain/repository/NotificationRepository.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/NotificationAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
Labels: fix

#77 [FEAT] #6 - Search
  data/src/main/java/com/woowahan/data/base/BaseDataSource.kt
  data/src/main/java/com/woowahan/data/entity/RepositoryData.kt
  data/src/main/java/com/woowahan/data/entity/SearchData.kt
  data/src/main/java/com/woowahan/data/search/SearchDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/search/SearchPagingSource.kt
  data/src/main/java/com/woowahan/data/search/SearchRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/search/SearchService.kt
  data/src/main/java/com/woowahan/data/user/UserDataSourceImpl.kt
  data/src/main/java/com/woowahan/data/user/UserRepositoryImpl.kt
  data/src/main/java/com/woowahan/data/user/UserService.kt
  domain/src/main/java/com/woowahan/domain/model/Repository.kt
  domain/src/main/java/com/woowahan/domain/model/Search.kt
  domain/src/main/java/com/woowahan/domain/repository/SearchRepository.kt
  domain/src/main/java/com/woowahan/domain/repository/UserRepository.kt
  domain/src/main/java/com/woowahan/domain/searchUseCase/GetSearchResultUseCase.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/DataSourceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RepositoryModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/ServiceModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/UseCaseModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/RecyclerViewStateAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/SearchResultAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ColorRand.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/StarFormatter.kt
  presentation/src/main/res/drawable/bg_search_selector.xml
  presentation/src/main/res/drawable/ic_star_yellow.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/item_footer.xml
  presentation/src/main/res/layout/item_search.xml
  presentation/src/main/res/layout/layout_load_error_checker.xml
  presentation/src/main/res/values/strings.xml
Labels: feature, pair

#81 [FIX] #80 - Search Checker 수정
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/layout_load_error_checker.xml
Labels: bug, fix

#93 Feature/41 notification infinite scroll - Loading 추가
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/res/layout/fragment_notification.xml
Labels: feature

#94 [FEAT] #85 - Set 700milisecond before searching
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
Labels: enhancement

#100 [FIX] #98 login 화면 버그 수정
  data/src/main/java/com/woowahan/data/entity/GitHubTokenData.kt
  domain/src/main/java/com/woowahan/domain/model/GitToken.kt
  presentation/build.gradle
  presentation/src/main/java/com/woowahan/repositorysearch/di/module/RetrofitModule.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ApiHeaderInterceptor.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/DataStore.kt
  presentation/src/main/res/layout/activity_login.xml
Labels: fix

#111 [FEAT] #110 - Show keyboard in search fragment
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
Labels: feature

#115 [REFECTOR] #112
  data/src/main/java/com/woowahan/data/issue/IssueRepositoryImpl.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/RecyclerViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/TabLayoutBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/FilterAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/IssueAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/NotificationAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/SearchResultAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ColorCreator.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ColorRand.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/StarFormatter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/TimeFormatter.kt
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_issue.xml
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/item_issue.xml
  presentation/src/main/res/layout/item_notification.xml
  presentation/src/main/res/layout/item_search.xml
  presentation/src/main/res/layout/layout_load_error_checker.xml
  presentation/src/main/res/values/array.xml
Labels: refector

#116 [FIX] #114 - 키보드 안보이던 버그 해결
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
Labels: bug, fix

#117 [DEV] Release 1.1
  .DS_Store
  .gitignore
  .idea/.gitignore
  .idea/.name
  .idea/compiler.xml
  .idea/deploymentTargetDropDown.xml
  .idea/discord.xml
  .idea/misc.xml
  data/.DS_Store
  data/.gitignore
  data/src/.DS_Store
  data/src/main/.DS_Store
  data/src/main/java/.DS_Store
  data/src/main/java/com/.DS_Store
  data/src/main/java/com/woowahan/data/issue/IssueRepositoryImpl.kt
  domain/.DS_Store
  domain/.gitignore
  domain/src/.DS_Store
  domain/src/main/.DS_Store
  domain/src/main/java/.DS_Store
  domain/src/main/java/com/.DS_Store
  presentation/.DS_Store
  presentation/.gitignore
  presentation/build.gradle
  presentation/src/main/.DS_Store
  presentation/src/main/java/com/woowahan/repositorysearch/extension/ImageViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/RecyclerViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/TabLayoutBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/extension/TextViewBindingAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/FilterAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/IssueAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/NotificationAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/adapter/SearchResultAdapter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/login/LoginViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/MainActivity.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/IssueViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/main/fragment/NotificationViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/ProfileViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchFragment.kt
  presentation/src/main/java/com/woowahan/repositorysearch/ui/result/fragment/SearchViewModel.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ColorCreator.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/ColorRand.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/StarFormatter.kt
  presentation/src/main/java/com/woowahan/repositorysearch/util/TimeFormatter.kt
  presentation/src/main/res/.DS_Store
  presentation/src/main/res/layout/activity_login.xml
  presentation/src/main/res/layout/activity_main.xml
  presentation/src/main/res/layout/fragment_issue.xml
  presentation/src/main/res/layout/fragment_notification.xml
  presentation/src/main/res/layout/fragment_profile.xml
  presentation/src/main/res/layout/fragment_search.xml
  presentation/src/main/res/layout/item_issue.xml
  presentation/src/main/res/layout/item_notification.xml
  presentation/src/main/res/layout/item_search.xml
  presentation/src/main/res/layout/layout_load_error_checker.xml
  presentation/src/main/res/values/array.xml
Labels: pair
